#无法启动时，去nacos目录下删除data文件
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-order?useSSL=false
    username: root
    password: fy199
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos的地址
      discovery:
        #集群名称
        luster-name: SHANGHAI
        #命名空间,同一个空间才能联系
        #namespace: 41453fa6-9e3d-4380-aac6-0e410772e024 #dev环境
        ephemeral: false #非临时实例
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel的控制地址
      web-context-unify: false
#      datasource:
#        flow: #限流规则
#          nacos:
#            server-addr: localhost:8848 #nacos地址
#            dataId: orderservice-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: flow
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
#feign:  feign具有负载均衡
#  client:
#    config:
#      default:
#        loggerLevel: FULL  全部日志打印
feign:
  httpclient:
    enabled: true
    max-connections: 100 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
  #sentinel:
    #enabled: true


