server:
  port: 10010 #网关端口

spring:
  application:
    name: gateway   #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:  #网关路由配置
        - id: user-service    #路由id，自定义，唯一即可
          uri: lb://userservice #lb是负载均衡，后面是服务器名称
          predicates:           #路由断言
             - Path=/user/**     #按路径匹配
        - id: order-service
          uri: lb://orderservice
          predicates:
             - Path=/order/**
             - Before=2023-11-11T15:20:20.433+08:00[Asia/Shanghai]
      default-filters:
        - AddRequestHeader=truth,fy is niubiest
        - AddRequestHeader=origin,gateway
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
